version: "3"
services:
  ho11y:
    image: public.ecr.aws/mhausenblas/ho11y:stable
    ports:
      - 8765:8765 # <1>
    logging: # <2>
      driver: fluentd
      options:
        tag: ho11y
    depends_on: # <3>
      - fluent-bit

  fluent-bit:
    image: fluent/fluent-bit:1.9.6
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf # <1>
    ports:
      - "24224:24224" # <2>
      - "24224:24224/udp"
    depends_on:
      - opensearch-node1

  opensearch-node1:
    image: opensearchproject/opensearch:2.1.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200 # <1>

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.1.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # <2>
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]' # <3>
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

volumes:
  opensearch-data1:
